### ISSUE TITLE
Problems with reading data for `s10_graph_based_slam`

### ISSUE THREAD

**Issue by dorecasan** [conorhennessy/Computer-Vision-Playground#1]
Data in `s10_graph_based_slam` seems to have some problems, I can not load in Matlab.
```cplusplus
Error using load
Unknown text on line number 1 of ASCII file ../data/simulation-pose-pose.dat
"MATLAB".

Error in lsSLAM (line 11)
load('../data/simulation-pose-pose.dat')
```
Thank you

**Comment by conorhennessy** [comment]
Hi @dorecasan, apologies for the delay in getting back to you. Thank you for reporting an issue!

It looks like you were running the code for task sheet 10 for the graph based slam topic, I have just tested the current code with the existing datasets. All has been able to run grand. As shown below here:
![screenshot](https://user-images.githubusercontent.com/9257022/112674626-0d87b680-8e5e-11eb-9a60-1cd21d525b1c.png)

Please do try to run this code in Octave. Further details & download [here](https://www.gnu.org/software/octave/download)
Make sure that you pick the right directory to run this in, in octave.


These solutions were created & tested in Octave 5.2.0.
The code should also be compatible to run in MATLAB. However, this has not been tested. Seems like you have found an issue there! 😊
More about conversion and differences between Octave & MATLAB can be found [here](https://en.wikibooks.org/wiki/MATLAB_Programming/Differences_between_Octave_and_MATLAB).

**Comment by dorecasan** [comment]
Thank you so much for your reply. I will try again.
